### ISSUE TITLE
Can't SSH into the VM

### ISSUE THREAD

**Issue by eofafrica4lyf** [Meshlab-HSN/IT_sys_perf_2425#21]
<img width="661" alt="image" src="https://github.com/user-attachments/assets/5bcc9a1e-ad74-4d28-945f-6decb930e3b6">

I have an existing config file, so I added the lines at the bottom like in the attached image.
My team is 12.
I used no password while creating the keys.

**Comment by eofafrica4lyf** [comment]
<img width="665" alt="image" src="https://github.com/user-attachments/assets/671a53d9-9071-4f70-a2d9-336931d4288c">
 
It's asking me for a password. 
I'm not sure if there is a mistake or because there is something that needs to be done at your end.

**Comment by tk154** [comment]
You need to use your private key instead of the .pub public key inside your config file
